//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastabakim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class klinikEntities : DbContext
    {
        public klinikEntities()
            : base("name=klinikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bakim> bakim { get; set; }
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<hasta> hasta { get; set; }
        public virtual DbSet<ilac> ilac { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<personel> personel { get; set; }
    }
}
